data_server = "None"

[[locations]]
regex = '.*'
substitution_string = '$0'

backend.kind = "S3"
backend.bucket = "data"
# The minio endpoint is set as the minio service within docker compose.
backend.endpoint = "http://minio:9000"
# Optionally, force path style addressing.
#backend.path_style = true
