[package]
name = "htsget-lambda"
version = "0.5.2"
rust-version = "1.83"
authors = ["Marko Malenic <mmalenic1@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2021"
license = "MIT"
description = "A cloud-based instance of htsget-rs using AWS Lambda, which serves data according to the htsget protocol."
documentation = "https://github.com/umccr/htsget-rs/blob/main/htsget-lambda/README.md"
homepage = "https://github.com/umccr/htsget-rs/blob/main/htsget-lambda/README.md"
repository = "https://github.com/umccr/htsget-rs"

[features]
aws = ["htsget-axum/aws", "htsget-config/aws", "htsget-search/aws", "htsget-http/aws", "htsget-test/aws"]
url = ["htsget-axum/url", "htsget-config/url", "htsget-search/url", "htsget-http/url", "htsget-test/url"]
experimental = [
    "htsget-axum/experimental",
    "htsget-config/experimental",
    "htsget-search/experimental",
    "htsget-http/experimental",
    "htsget-test/experimental"
]
default = []

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6", features = ["cors"] }
rustls = "0.23"
lambda_http = { version = "0.13" }
lambda_runtime = { version = "0.13" }
serde = { version = "1" }
serde_json = "1"
mime = "0.3"
regex = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
bytes = "1"

htsget-config = { version = "0.12.0", path = "../htsget-config", default-features = false }
htsget-search = { version = "0.9.1", path = "../htsget-search", default-features = false }
htsget-http = { version = "0.5.1", path = "../htsget-http", default-features = false }
htsget-test = { version = "0.7.1", path = "../htsget-test", features = ["http"], default-features = false }
htsget-axum = { version = "0.2.2", path = "../htsget-axum", default-features = false }

[dev-dependencies]
async-trait = "0.1"
query_map = { version = "0.7", features = ["url-query"] }
tempfile = "3"
